name: release

on: release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - id: checkout_action
      uses: actions/checkout@v1
    - name: Publish release
      uses: mariamrf/py-package-publish-action@v0.0.2
      env:
        PYTHON_VERSION: 3.7
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
